# 1. IPAddressPool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.60.0/24
  autoAssign: true

---
# 2. BGPPeer
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgp-peer-1
  namespace: metallb-system
spec:
  myASN: 65001
  peerASN: 65000
  peerAddress: 192.168.22.50
  # Optional: Add hold time and keepalive
  holdTime: "90s"
  keepaliveTime: "30s"

---
# 3. BGPAdvertisement
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: main-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - main-pool  # Must match IPAddressPool name above
  peers:
  - bgp-peer-1  # Must match BGPPeer name above
  aggregationLength: 32  # This ensures /32 routes for individual services
  # Optional: Add communities if needed
  # communities:
  # - "65001:100"

---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb-advanced
  namespace: metallb-system
spec:
  # FRR-K8s backend for advanced routing features
  bgpBackend: frr-k8s
  
  # Debug logging to troubleshoot /32 route advertisement issues
  logLevel: debug

---
# 4. FRRConfiguration (for receiving routes)
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: frr-config
  namespace: metallb-system
spec:
  bgp:
    routers:
    - asn: 65001
      neighbors:
      - address: 192.168.22.50
        asn: 65000
        toReceive:
          allowed:
            mode: all
