apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-cephfs-pvc
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-external-storagecluster-cephfs
